-- ============================================================
-- SEED: hrbp_sop_definitions
-- 8 rows — SOP-1 through SOP-8
-- Source: HRBP Playbook Section 4
-- ============================================================

INSERT INTO hrbp_sop_definitions
    (sop_type, number, name, description, trigger_source,
     kra_tags, control_level, email_templates,
     persons_hierarchy, steps_definition)
VALUES

-- ============================================================
-- SOP-1: Regular Engagement
-- ============================================================
('SOP-1', 'SOP-1', 'Regular Engagement',
 'Ongoing cadence with every active J2Wite from Day 1 onwards. This is the baseline SOP that runs continuously for every consultant.',
 'scheduler',
 ARRAY['K3', 'K4'],
 'HIGH',
 ARRAY['E1', 'E2', 'E10'],
 '[
   {"order": 1, "role": "hrbp",     "label": "HRBP",             "sla_window": "ongoing"},
   {"order": 2, "role": "ops_head", "label": "Operations Head",  "sla_window": "escalation only"}
 ]'::jsonb,
 '[
   {"number": 1, "action_label": "Day 1 intro — WhatsApp + email within 2 hours", "action_detail": "Send E2 template. Introduce yourself as career partner not HR admin.", "owner_role": "hrbp", "sla_working_hours": 2, "escalate_to_role": "ops_head", "email_template_id": "E2", "hard_gate": null, "kra_ref": "K3"},
   {"number": 2, "action_label": "Day 15 connect — video or in-person", "action_detail": "Check system access, manager clarity, project clarity, first impressions.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": "E1", "hard_gate": null, "kra_ref": "K3"},
   {"number": 3, "action_label": "Day 45 joint lock — HRBP + BH together", "action_detail": "Is J2Wite settling? Client happy? Lock 1-year intent. Use the Day 45 script from playbook.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "bh", "email_template_id": null, "hard_gate": null, "kra_ref": "K3"},
   {"number": 4, "action_label": "Day 60 tier classification", "action_detail": "Classify cohort: Star / High Performer / Rising / Bedrock / Watch / Rescue.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 5, "action_label": "Day 90 first quarterly review", "action_detail": "Top 20%: rate revision check. Bottom 20%: PIP starts.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": "E1", "hard_gate": null, "kra_ref": "K4"},
   {"number": 6, "action_label": "Bi-weekly check-in email", "action_detail": "Send E1 template every 14 days. Track non-responders. 2 missed cycles = escalate.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": "E1", "hard_gate": null, "kra_ref": "K3"},
   {"number": 7, "action_label": "Monthly BH call", "action_detail": "One call per account. Use Q3 BH template. Capture written feedback.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 8, "action_label": "Quarterly NPS survey dispatch", "action_detail": "5-question survey. Target 80% response rate. Act on score below 7 within 7 days.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K3"},
   {"number": 9, "action_label": "Day-end report to Operations Head", "action_detail": "Send E10 template daily by 6 PM. Contacts, red flags, exits, BH calls, pending items.", "owner_role": "hrbp", "sla_working_hours": 1, "escalate_to_role": "ops_head", "email_template_id": "E10", "hard_gate": null, "kra_ref": "K3"}
 ]'::jsonb),

-- ============================================================
-- SOP-2: Voluntary Resignation
-- ============================================================
('SOP-2', 'SOP-2', 'Voluntary Resignation',
 'Triggered when a resignation is received via any channel. Retain first — always. Never confirm LWD until BH and client confirm.',
 'email_classified|hrbp_manual',
 ARRAY['K1'],
 'HIGH',
 ARRAY['E3', 'E8'],
 '[
   {"order": 1, "role": "hrbp", "label": "HRBP",                 "sla_window": "0 to 168 hrs (steps 1–5)"},
   {"order": 2, "role": "bh",   "label": "Business Head",         "sla_window": "48 hrs (step 6)"},
   {"order": 3, "role": "hrbp", "label": "HRBP (Post-Decision)",  "sla_window": "post-decision (steps 7–10)"}
 ]'::jsonb,
 '[
   {"number": 1,  "action_label": "Capture resignation — do NOT confirm LWD",     "action_detail": "Log within 1 hr. Acknowledge receipt only. Do NOT confirm LWD. Send E3 template.",                                                                          "owner_role": "hrbp", "sla_working_hours": 1,    "escalate_to_role": "bh",       "email_template_id": "E3", "hard_gate": "BLOCK_LWD_CONFIRMATION",        "kra_ref": "K1", "medium": "email",               "medium_config": {"template_id": "E3", "instruction": "Send the E3 acknowledgement template to the consultant. Do NOT mention or confirm Last Working Day."}},
   {"number": 2,  "action_label": "Prepare comprehensive retention plan",           "action_detail": "Assess tier, PO, reason, retention feasibility. Document before any conversation. No engagement without a plan.",                                            "owner_role": "hrbp", "sla_working_hours": 2,    "escalate_to_role": "ops_head", "email_template_id": null,  "hard_gate": null,                             "kra_ref": "K1", "medium": "document",            "medium_config": {"instruction": "Upload the retention plan document before initiating any conversation with the consultant.", "accepted_formats": ["pdf", "docx"], "max_files": 1}},
   {"number": 3,  "action_label": "Same-day 1:1 within 4 hours",                   "action_detail": "Listen 80%, talk 20%. Capture: CTC, offer in hand, expected CTC, willing to stay?",                                                                         "owner_role": "hrbp", "sla_working_hours": 4,    "escalate_to_role": "bh",       "email_template_id": null,  "hard_gate": null,                             "kra_ref": "K1", "medium": "form",                "medium_config": {"instruction": "Complete the 1:1 with the consultant and fill in the details below.", "form_schema": [{"key": "current_ctc", "label": "Current CTC (₹)", "type": "number", "required": true}, {"key": "offer_in_hand", "label": "Offer in Hand (₹)", "type": "number", "required": false}, {"key": "offer_company", "label": "Offer from (Company)", "type": "text", "required": false}, {"key": "expected_ctc", "label": "Expected CTC (₹)", "type": "number", "required": true}, {"key": "willing_to_stay", "label": "Willing to Stay?", "type": "boolean", "required": true}, {"key": "retention_feasibility", "label": "Retention Feasibility Notes", "type": "textarea", "required": false}]}},
   {"number": 4,  "action_label": "Classify risk level",                            "action_detail": "RED: Top 20% and PO above Rs.3L. AMBER: Mid 60%. GREEN: Bottom 20%.",                                                                                       "owner_role": "hrbp", "sla_working_hours": 8,    "escalate_to_role": "ops_head", "email_template_id": null,  "hard_gate": null,                             "kra_ref": "K1", "medium": "rag",                 "medium_config": {"instruction": "Classify the consultant based on performance tier and PO value.", "rag_options": [{"value": "red", "label": "RED", "description": "Top 20% performer and PO above ₹3L — highest retention priority"}, {"value": "amber", "label": "AMBER", "description": "Mid 60% — moderate retention priority"}, {"value": "green", "label": "GREEN", "description": "Bottom 20% — lower retention priority"}]}},
   {"number": 5,  "action_label": "Brief BH with full summary",                    "action_detail": "Summary to BH within 24 hrs: name, tier, PO, reason, offer in hand, HRBP assessment.",                                                                      "owner_role": "hrbp", "sla_working_hours": 24,   "escalate_to_role": "ops_head", "email_template_id": null,  "hard_gate": null,                             "kra_ref": "K1", "medium": "document_ai_summary", "medium_config": {"instruction": "Upload the BH briefing document. An AI summary will be generated for quick visibility.", "accepted_formats": ["pdf", "docx"], "max_files": 1}},
   {"number": 6,  "action_label": "BH makes retention decision",                   "action_detail": "BH evaluates within 48 hrs. Finance checks comp. Decision in 5 working days.",                                                                               "owner_role": "bh",   "sla_working_hours": 48,   "escalate_to_role": "ops_head", "email_template_id": null,  "hard_gate": null,                             "kra_ref": "K1", "medium": "comment",             "medium_config": {"instruction": "Document the retention decision and the rationale below.", "placeholder": "State the retention decision (RETAIN / EXIT) and the reasoning behind it..."}},
   {"number": 7,  "action_label": "If RETAIN — confirm and get written withdrawal", "action_detail": "Offer via BH not HRBP. Written withdrawal from J2Wite mandatory. Update tracker. Fortnightly 1:1 for 3 months.",                                            "owner_role": "hrbp", "sla_working_hours": 24,   "escalate_to_role": "ops_head", "email_template_id": "E8", "hard_gate": "REQUIRE_WRITTEN_WITHDRAWAL",     "kra_ref": "K1", "medium": "comment",             "medium_config": {"instruction": "Confirm written withdrawal has been received and logged. Add the tracker update notes.", "placeholder": "Confirm written withdrawal received. Note the retention offer details and next 1:1 schedule..."}},
   {"number": 8,  "action_label": "If EXIT — confirm LWD and start redeployment",  "action_detail": "Confirm LWD only after BH and client align. KT plan. Circulate CV to all BHs.",                                                                             "owner_role": "hrbp", "sla_working_hours": 168,  "escalate_to_role": "ops_head", "email_template_id": null,  "hard_gate": "REQUIRE_BH_AND_CLIENT_SIGNOFF",  "kra_ref": "K1", "medium": "comment",             "medium_config": {"instruction": "Confirm LWD, KT plan details, and CV circulation status.", "placeholder": "Confirmed LWD: [date]. KT plan: [details]. CV circulated to BHs: [list]..."}},
   {"number": 9,  "action_label": "Post-retention watch — 90 days mandatory",      "action_detail": "Fortnightly 1:1 and monthly BH check mandatory for 90 days. Retained J2Wite is vulnerable.",                                                                "owner_role": "hrbp", "sla_working_hours": 2160, "escalate_to_role": "ops_head", "email_template_id": "E1", "hard_gate": null,                             "kra_ref": "K1", "medium": "comment",             "medium_config": {"instruction": "Log the 90-day watch progress. Record each fortnightly 1:1 and monthly BH check.", "placeholder": "Date of last 1:1: [date]. Consultant sentiment: [notes]. BH check status: [notes]..."}},
   {"number": 10, "action_label": "Exit interview — last week of notice",           "action_detail": "Capture real reason. Update dashboard. Must be completed before last working day.",                                                                          "owner_role": "hrbp", "sla_working_hours": 168,  "escalate_to_role": "ops_head", "email_template_id": null,  "hard_gate": null,                             "kra_ref": "K1", "medium": "status_update",       "medium_config": {"instruction": "Mark the exit interview status and capture the real reason for leaving.", "status_options": [{"value": "completed", "label": "Completed — real reason captured"}, {"value": "scheduled", "label": "Scheduled — awaiting completion"}, {"value": "not_reachable", "label": "Consultant not reachable"}, {"value": "waived", "label": "Waived (client/time constraint)"}], "extra_fields": [{"key": "real_reason", "label": "Real Reason for Leaving", "type": "textarea", "required": true}, {"key": "exit_date", "label": "Last Working Day", "type": "date", "required": true}]}}
 ]'::jsonb),

-- ============================================================
-- SOP-3: Contract Closure and Redeployment
-- ============================================================
('SOP-3', 'SOP-3', 'Contract Closure and Redeployment',
 'Flag 4 months before PO end — not 90 days. Earlier flag = more time for BH to renew with client.',
 'scheduler',
 ARRAY['K2'],
 'MEDIUM',
 ARRAY['E5'],
 '[
   {"order": 1, "role": "hrbp",     "label": "HRBP",            "sla_window": "4 months before"},
   {"order": 2, "role": "bh",       "label": "Business Head",   "sla_window": "3.5 months before"},
   {"order": 3, "role": "ops_head", "label": "Operations Head", "sla_window": "1 month before"},
   {"order": 4, "role": "coo",      "label": "COO + Priti",     "sla_window": "under 1 month"}
 ]'::jsonb,
 '[
   {"number": 1, "action_label": "4-month flag — add to Contract Review cohort", "action_detail": "System or PO team flags POs ending in 4 months. HRBP updates tracker and alerts BH.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K2"},
   {"number": 2, "action_label": "BH initiates renewal with client by 3.5-month mark", "action_detail": "BH contacts client directly. HRBP is NOT in this conversation.", "owner_role": "bh", "sla_working_hours": 40, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K2"},
   {"number": 3, "action_label": "HRBP connects with J2Wite at 3 months before", "action_detail": "Reassure: Bollama is managing your renewal. No disruption expected. Assess preference. Send E5.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": "E5", "hard_gate": null, "kra_ref": "K2"},
   {"number": 4, "action_label": "Collect updated CV within 48 hours", "action_detail": "Share updated CV with all BHs immediately.", "owner_role": "hrbp", "sla_working_hours": 48, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K2"},
   {"number": 5, "action_label": "Active redeployment — 2 months before", "action_detail": "Client confirms non-extension. BH notifies HRBP same day. HRBP informs J2Wite within 4 hrs.", "owner_role": "hrbp", "sla_working_hours": 4, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K2"},
   {"number": 6, "action_label": "No redeployment by 1 month — escalate", "action_detail": "Operations Head and Priya notified. Daily tracking. HRBP and BH on daily calls.", "owner_role": "ops_head", "sla_working_hours": 8, "escalate_to_role": "coo", "email_template_id": null, "hard_gate": null, "kra_ref": "K2"},
   {"number": 7, "action_label": "Day 0 — Redeploy or Close", "action_detail": "Redeployed: new PO before Day 0. Closure: letter on last day. F&F per policy.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K2"}
 ]'::jsonb),

-- ============================================================
-- SOP-4: Conversion / NOC Request
-- ============================================================
('SOP-4', 'SOP-4', 'Conversion and NOC Request',
 'Client wants to hire J2Wite directly. Approximately 8.5% conversion fee. Priti sign-off mandatory. NOC without Priti is not valid.',
 'email_classified|hrbp_manual',
 ARRAY['K2'],
 'MEDIUM',
 ARRAY['E6A', 'E6B'],
 '[
   {"order": 1, "role": "bh",   "label": "Business Head",       "sla_window": "same day (step 1)"},
   {"order": 2, "role": "hrbp", "label": "HRBP",                "sla_window": "24–48 hrs (steps 2–3)"},
   {"order": 3, "role": "bh",   "label": "Business Head",       "sla_window": "24–48 hrs (steps 4–6)"},
   {"order": 4, "role": "ceo",  "label": "CEO",                 "sla_window": "24 hrs (step 7)"},
   {"order": 5, "role": "bh",   "label": "Business Head (NOC)", "sla_window": "24 hrs (step 8)"},
   {"order": 6, "role": "hrbp", "label": "HRBP (Exit)",         "sla_window": "8 hrs (step 9)"}
 ]'::jsonb,
 '[
   {"number": 1, "action_label": "Alert HRBP & Account Manager same day", "action_detail": "BH or HRBP hears conversion intent. Alert both HRBP and Account Manager the same day. Do NOT discuss with J2Wite or client yet.", "owner_role": "bh", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K2", "medium": "email", "medium_config": {"instruction": "Send an internal alert email to the HRBP and Account Manager about the conversion intent. Do NOT loop in the consultant or client at this stage."}},
   {"number": 2, "action_label": "Check MSA eligibility — min tenure clause", "action_detail": "Verify MSA clause: minimum tenure for conversion is 12 to 24 months. Check with Invoice Team.", "owner_role": "hrbp", "sla_working_hours": 24, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K2", "medium": "status_update", "medium_config": {"instruction": "Check the MSA eligibility clause with the Invoice Team and update the status below.", "status_options": [{"value": "eligible", "label": "Eligible — MSA clause satisfied"}, {"value": "not_eligible", "label": "Not Eligible — MSA clause not met"}, {"value": "pending_check", "label": "Pending — checking with Invoice Team"}], "extra_fields": [{"key": "tenure_months", "label": "Consultant Tenure (months)", "type": "number", "required": true}, {"key": "msa_notes", "label": "MSA Eligibility Notes", "type": "textarea", "required": false}]}},
   {"number": 3, "action_label": "Connect with J2Wite within 48 hours", "action_detail": "Understand intent. Listen only — do NOT influence decision.", "owner_role": "hrbp", "sla_working_hours": 48, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K2", "medium": "comment", "medium_config": {"instruction": "Connect with the consultant and listen to their intent. Do NOT influence the decision. Log the conversation summary below.", "placeholder": "Describe the conversation: consultant intent, concerns raised, sentiment, any retention signals..."}},
   {"number": 4, "action_label": "BH evaluates counter-offer within 48 hours", "action_detail": "If retention possible, BH makes offer within 48 hrs.", "owner_role": "bh", "sla_working_hours": 48, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K2", "medium": "comment", "medium_config": {"instruction": "Evaluate if a counter-offer for retention is feasible. Document the evaluation and outcome below.", "placeholder": "Is retention possible? What offer was evaluated or made? Final decision: proceed with conversion or attempt retention?..."}},
   {"number": 5, "action_label": "Client submits NOC request in standard format", "action_detail": "Format: Consultant name, Employee ID, WO Number, PO End Date, Proposed Conversion Date.", "owner_role": "bh", "sla_working_hours": 24, "escalate_to_role": "ops_head", "email_template_id": "E6A", "hard_gate": null, "kra_ref": "K2", "medium": "document", "medium_config": {"instruction": "Receive the NOC request from the client in the standard format and upload it here. Required fields: Consultant name, Employee ID, WO Number, PO End Date, Proposed Conversion Date.", "accepted_formats": ["pdf", "docx"], "max_files": 1}},
   {"number": 6, "action_label": "BH submits to Priti — fee, MSA, PO impact", "action_detail": "BH submits to Priti with conversion fee, MSA clause, PO impact details. Priti responds within 24 working hours.", "owner_role": "bh", "sla_working_hours": 24, "escalate_to_role": "coo", "email_template_id": null, "hard_gate": null, "kra_ref": "K2", "medium": "document", "medium_config": {"instruction": "Prepare and upload the submission document for Priti (COO) covering: conversion/absorption fee (~8.5%), MSA clause reference, and PO financial impact.", "accepted_formats": ["pdf", "docx"], "max_files": 2}},
   {"number": 7, "action_label": "CEO reviews and approves or rejects the NOC", "action_detail": "CEO reviews the NOC request. Approves or rejects. Decision must be documented.", "owner_role": "ceo", "sla_working_hours": 24, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K2", "medium": "status_update", "medium_config": {"instruction": "Review the NOC request and provide your decision. Approval is required before the NOC can be issued.", "status_options": [{"value": "approved", "label": "Approved — NOC granted"}, {"value": "rejected", "label": "Rejected — NOC denied"}, {"value": "more_info_needed", "label": "More Information Needed"}], "extra_fields": [{"key": "decision_comments", "label": "Decision Comments / Reasoning", "type": "textarea", "required": true}]}},
   {"number": 8, "action_label": "NOC issued after Priti approval — notify Invoice Team", "action_detail": "BH issues NOC via E6A or E6B template. Invoice Team notified.", "owner_role": "bh", "sla_working_hours": 24, "escalate_to_role": "ops_head", "email_template_id": "E6A", "hard_gate": "REQUIRE_PRITI_APPROVAL", "kra_ref": "K2", "medium": "email", "medium_config": {"instruction": "CEO/Priti has approved the NOC. Issue the NOC via E6A or E6B template and send to the Invoice Team.", "template_id": "E6A"}},
   {"number": 9, "action_label": "Clean exit — LWD confirmed, exit interview done", "action_detail": "HRBP confirms LWD. Exit interview. Update tracker: reason = Conversion to Client.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K2", "medium": "status_update", "medium_config": {"instruction": "Confirm the Last Working Day and complete the exit interview. Update the tracker with reason = Conversion to Client.", "status_options": [{"value": "lwd_confirmed", "label": "LWD Confirmed with consultant and client"}, {"value": "exit_interview_done", "label": "Exit Interview Completed"}, {"value": "tracker_updated", "label": "Tracker Updated — reason: Conversion to Client"}], "extra_fields": [{"key": "last_working_day", "label": "Last Working Day", "type": "date", "required": true}, {"key": "exit_interview_notes", "label": "Exit Interview Notes", "type": "textarea", "required": true}]}}
 ]'::jsonb),

-- ============================================================
-- SOP-5: Performance Issues and PIP
-- ============================================================
('SOP-5', 'SOP-5', 'Performance Issues and PIP',
 'Document before acting. No documentation = no PIP. Weekly reviews are non-negotiable.',
 'hrbp_manual|signal_threshold',
 ARRAY['K4'],
 'HIGH',
 ARRAY['E7'],
 '[
   {"order": 1, "role": "hrbp",     "label": "HRBP + Manager", "sla_window": "0 to 5 days"},
   {"order": 2, "role": "bh",       "label": "Business Head",  "sla_window": "5 to 15 days"},
   {"order": 3, "role": "ops_head", "label": "Operations Head","sla_window": "15 to 30 days"},
   {"order": 4, "role": "ceo",    "label": "CEO",          "sla_window": "Day 30 termination decision"}
 ]'::jsonb,
 '[
   {"number": 1, "action_label": "Manager documents specific incidents with evidence", "action_detail": "Manager documents incidents with dates and evidence. HRBP validates specificity. No vague complaints.", "owner_role": "hrbp", "sla_working_hours": 48, "escalate_to_role": "bh", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 2, "action_label": "HRBP and BH decide — coaching, PIP, or exit", "action_detail": "Do NOT inform client before internal decision is made.", "owner_role": "hrbp", "sla_working_hours": 48, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 3, "action_label": "PIP initiation — J2Wite signs 30-day plan", "action_detail": "HRBP + Manager + J2Wite meeting. Share PIP document with specific goals and 30-day timeline. J2Wite must sign.", "owner_role": "hrbp", "sla_working_hours": 40, "escalate_to_role": "ops_head", "email_template_id": "E7", "hard_gate": null, "kra_ref": "K4"},
   {"number": 4, "action_label": "Weekly PIP review — every 5 working days", "action_detail": "HRBP + Manager + J2Wite. Document progress. Review missed = immediate escalation to BH and Operations Head.", "owner_role": "hrbp", "sla_working_hours": 40, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 5, "action_label": "Day 15 mid-assessment", "action_detail": "Improving or not improving. If not improving: start quiet replacement sourcing.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 6, "action_label": "Day 30 final assessment", "action_detail": "PASS: close PIP and document. FAIL: termination process begins immediately.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ceo", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 7, "action_label": "If FAIL — termination with Priti approval", "action_detail": "Priti MUST be informed and approve before execution. Client informed by BH. Replacement starts Day 0.", "owner_role": "bh", "sla_working_hours": 48, "escalate_to_role": "coo", "email_template_id": null, "hard_gate": "REQUIRE_PRITI_APPROVAL", "kra_ref": "K4"}
 ]'::jsonb),

-- ============================================================
-- SOP-6: Difficult Consultant and Misconduct
-- ============================================================
('SOP-6', 'SOP-6', 'Difficult Consultant and Misconduct',
 'Act on signals before the client or leadership escalates. Early action = control. Late action = crisis.',
 'signal_threshold|hrbp_manual',
 ARRAY['K4'],
 'MEDIUM',
 ARRAY[]::text[],
 '[
   {"order": 1, "role": "hrbp",     "label": "HRBP",             "sla_window": "same day"},
   {"order": 2, "role": "bh",       "label": "Business Head",    "sla_window": "within 24 hrs"},
   {"order": 3, "role": "ops_head", "label": "Ops Head + Legal", "sla_window": "social media or escalation"}
 ]'::jsonb,
 '[
   {"number": 1, "action_label": "Detect 2 or more S4 signals — document immediately", "action_detail": "Document with date and source immediately. Must be done within 24 hrs of detection.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 2, "action_label": "Private 1:1 within 24 to 48 hours", "action_detail": "Do NOT accuse. Say: I noticed some things I want to understand. Listen first.", "owner_role": "hrbp", "sla_working_hours": 48, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 3, "action_label": "Document everything from the meeting", "action_detail": "Written record: date, what was said, J2Wite response. Must be done same day as meeting.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 4, "action_label": "Brief BH proactively — do not wait to be asked", "action_detail": "Tell BH: I have early signals on this person. Here is what I am doing. Within 24 hrs.", "owner_role": "hrbp", "sla_working_hours": 24, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 5, "action_label": "Decide — 30-day PIP or start quiet backfill", "action_detail": "If client has formed a view: quietly start replacement. Decision by Day 5.", "owner_role": "hrbp", "sla_working_hours": 40, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 6, "action_label": "If social media attack — do NOT respond individually", "action_detail": "Alert Operations Head and Legal same day. Legal team vets any response. Zero individual response.", "owner_role": "ops_head", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K4"},
   {"number": 7, "action_label": "Formal warning or termination — Priti sign-off required", "action_detail": "Priti sign-off before any termination. All documentation must be filed.", "owner_role": "bh", "sla_working_hours": 48, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": "REQUIRE_PRITI_APPROVAL", "kra_ref": "K4"}
 ]'::jsonb),

-- ============================================================
-- SOP-7: Absconding
-- ============================================================
('SOP-7', 'SOP-7', 'Absconding',
 'Day 1 of unannounced absence triggers the clock. Process is clear — follow exactly.',
 'hrbp_manual|attendance_flag',
 ARRAY['K1'],
 'HIGH',
 ARRAY[]::text[],
 '[
   {"order": 1, "role": "hrbp",     "label": "HRBP",            "sla_window": "0 to 2 hrs"},
   {"order": 2, "role": "bh",       "label": "Business Head",   "sla_window": "2 to 4 hrs"},
   {"order": 3, "role": "ops_head", "label": "Ops Head + Priti","sla_window": "Day 3"}
 ]'::jsonb,
 '[
   {"number": 1, "action_label": "Day 1 — call and WhatsApp within 2 hours", "action_detail": "Attendance flag or manager reports absence. HRBP calls and WhatsApps within 2 hrs.", "owner_role": "hrbp", "sla_working_hours": 2, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K1"},
   {"number": 2, "action_label": "BH informs client within 4 hours", "action_detail": "BH notifies client within 4 hrs. HRBP does NOT contact client directly.", "owner_role": "bh", "sla_working_hours": 4, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K1"},
   {"number": 3, "action_label": "Formal written communication by Day 1 EOD", "action_detail": "Email and WhatsApp: We noted your absence. Respond within 48 hrs.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K1"},
   {"number": 4, "action_label": "Day 2 follow-up — call, email, emergency contact", "action_detail": "Call and email again. Try emergency contact if available.", "owner_role": "hrbp", "sla_working_hours": 24, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K1"},
   {"number": 5, "action_label": "Day 3 — declare absconding, inform Priti immediately", "action_detail": "48 hrs no response = absconding confirmed. Priti informed immediately. No exceptions.", "owner_role": "hrbp", "sla_working_hours": 48, "escalate_to_role": "coo", "email_template_id": null, "hard_gate": null, "kra_ref": "K1"},
   {"number": 6, "action_label": "Termination letter issued within 24 hours", "action_detail": "HR Ops issues termination letter. No F&F. No relieving letter. Exit tracker updated.", "owner_role": "hrbp", "sla_working_hours": 24, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K1"}
 ]'::jsonb),

-- ============================================================
-- SOP-8: Medical Emergency
-- ============================================================
('SOP-8', 'SOP-8', 'Medical Emergency Critical Illness and Death',
 'For planned procedures J2Wite must inform HRBP before going to hospital. For emergencies family calls HRBP within 2 hours — NOT the insurance company.',
 'hrbp_manual',
 ARRAY['K3'],
 'HIGH',
 ARRAY['E14', 'E15', 'E16'],
 '[
   {"order": 1, "role": "hrbp",    "label": "HRBP",                 "sla_window": "within 2 hrs (steps 1–2)"},
   {"order": 2, "role": "finance", "label": "Finance",               "sla_window": "same day (steps 3–4)"},
   {"order": 3, "role": "hrbp",    "label": "HRBP",                 "sla_window": "same day to 24 hrs (steps 5–6)"},
   {"order": 4, "role": "finance", "label": "Finance (Escalation)",  "sla_window": "48 hrs (step 7)"},
   {"order": 5, "role": "hrbp",    "label": "HRBP (Closure)",       "sla_window": "up to 7 days (steps 8–10)"}
 ]'::jsonb,
 '[
   {"number": 1,  "action_label": "J2Wite or family alerts HRBP within 2 hours", "action_detail": "Planned: J2Wite informs HRBP before admission. Emergency: family calls HRBP within 2 hrs. Never call insurance company directly.", "owner_role": "hrbp", "sla_working_hours": 2, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "status_update", "medium_config": {"instruction": "Log the admission alert and update status. Do NOT call the insurance company directly — all communication goes through Finance.", "status_options": [{"value": "alerted", "label": "HRBP Alerted — admission confirmed"}, {"value": "emergency", "label": "Emergency Admission — family called within 2 hrs"}, {"value": "planned", "label": "Planned Admission — notified before admission"}, {"value": "monitoring", "label": "Monitoring — situation developing"}], "extra_fields": [{"key": "hospital_name", "label": "Hospital Name", "type": "text", "required": true}, {"key": "admission_type", "label": "Admission Type (Planned/Emergency)", "type": "text", "required": true}, {"key": "alert_log", "label": "Alert Log / Notes", "type": "textarea", "required": false}]}},
   {"number": 2,  "action_label": "HRBP calls Finance within 60 minutes", "action_detail": "Send E14 immediately. Finance must contact hospital billing within 60 mins. Planned: before admission. Emergency: within 60 mins.", "owner_role": "hrbp", "sla_working_hours": 1, "escalate_to_role": "ops_head", "email_template_id": "E14", "hard_gate": null, "kra_ref": "K3", "medium": "email", "medium_config": {"instruction": "Send E14 trigger email to Finance immediately. Finance must contact hospital billing within 60 minutes of this notification.", "template_id": "E14"}},
   {"number": 3,  "action_label": "Finance contacts hospital billing — same day", "action_detail": "Finance initiates J2W group insurance cashless claim. Provides TPA details. Send E16 to hospital.", "owner_role": "finance", "sla_working_hours": 1, "escalate_to_role": "ops_head", "email_template_id": "E16", "hard_gate": null, "kra_ref": "K3", "medium": "email", "medium_config": {"instruction": "Send E16 cashless claim initiation to hospital billing. Provide TPA details and initiate J2W group insurance cashless claim. Upload confirmation document if available.", "template_id": "E16"}},
   {"number": 4,  "action_label": "Finance assesses coverage within 24 hours", "action_detail": "Confirms insurance limit, current bill, projected total. Flags immediately if bill will exceed limit.", "owner_role": "finance", "sla_working_hours": 24, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "status_update", "medium_config": {"instruction": "Assess insurance coverage and file the coverage assessment report internally. Flag immediately if the bill is projected to exceed the insurance limit.", "status_options": [{"value": "within_limit", "label": "Within Limit — bill covered by insurance"}, {"value": "exceeds_limit", "label": "Exceeds Limit — escalation required to Priti/COO"}, {"value": "monitoring", "label": "Monitoring — projected total uncertain"}], "extra_fields": [{"key": "insurance_limit", "label": "Insurance Limit (₹)", "type": "number", "required": true}, {"key": "current_bill", "label": "Current Bill Amount (₹)", "type": "number", "required": true}, {"key": "projected_total", "label": "Projected Total (₹)", "type": "number", "required": true}, {"key": "assessment_notes", "label": "Coverage Assessment Notes", "type": "textarea", "required": false}]}},
   {"number": 5,  "action_label": "HRBP connects with family same day", "action_detail": "Warm, human, reassuring call. Send E15. J2W is handling insurance and billing. You focus on being with your family member.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": "E15", "hard_gate": null, "kra_ref": "K3", "medium": "email", "medium_config": {"instruction": "Send E15 family reassurance email. Follow up with a warm, personal call to the family. Reassure them that J2W is handling all insurance and billing — family should focus on their loved one.", "template_id": "E15"}},
   {"number": 6,  "action_label": "Daily updates — HRBP to Operations Head", "action_detail": "HRBP briefs Ops Head daily: condition, bill status, family needs, insurance status.", "owner_role": "hrbp", "sla_working_hours": 24, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "comment", "medium_config": {"instruction": "Send a daily condition briefing to the Operations Head covering: current medical condition, bill status, family needs, and insurance status. Log the briefing summary here.", "placeholder": "Daily briefing summary: medical condition update, current bill, insurance status, family needs, any escalation required..."}},
   {"number": 7,  "action_label": "If bill exceeds insurance limit — escalate to Priti", "action_detail": "Finance confirms overage to Priti and COO. Evaluate ex-gratia support. Family not told until decision made.", "owner_role": "finance", "sla_working_hours": 48, "escalate_to_role": "ceo", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "status_update", "medium_config": {"instruction": "Raise the overage escalation note to Priti and COO. Evaluate if ex-gratia support is applicable. Do NOT inform the family until a decision has been made.", "status_options": [{"value": "ex_gratia_approved", "label": "Ex-Gratia Approved — J2W will cover overage"}, {"value": "ex_gratia_rejected", "label": "Ex-Gratia Rejected — family to bear overage"}, {"value": "pending_decision", "label": "Pending Decision — Priti/COO reviewing"}], "extra_fields": [{"key": "overage_amount", "label": "Overage Amount (₹)", "type": "number", "required": true}, {"key": "escalation_notes", "label": "Escalation Notes for Priti/COO", "type": "textarea", "required": true}]}},
   {"number": 8,  "action_label": "If J2Wite recovers — return to work plan", "action_detail": "Finance processes reimbursement. HRBP follows up on return-to-work plan. BH informed of return date.", "owner_role": "hrbp", "sla_working_hours": 168, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "status_update", "medium_config": {"instruction": "Confirm recovery outcome. HRBP to coordinate return-to-work plan and ensure Finance processes any reimbursement. Upload medical fitness certificate if available.", "status_options": [{"value": "recovered_rtw", "label": "Recovered — Return to Work confirmed"}, {"value": "partial_recovery", "label": "Partial Recovery — phased return planned"}, {"value": "extended_leave", "label": "Extended Leave — return date TBD"}, {"value": "not_applicable", "label": "Not Applicable — outcome was not recovery"}], "extra_fields": [{"key": "return_date", "label": "Confirmed Return-to-Work Date", "type": "date", "required": false}, {"key": "rtw_notes", "label": "Return-to-Work Notes", "type": "textarea", "required": false}]}},
   {"number": 9,  "action_label": "If J2Wite passes away — inform Priti and COO immediately", "action_detail": "HRBP informs Ops Head, COO, Priti immediately. Finance initiates death benefit claim. Priority F&F. HRBP coordinates with family on formalities.", "owner_role": "hrbp", "sla_working_hours": 1, "escalate_to_role": "ceo", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "status_update", "medium_config": {"instruction": "If the J2Wite has passed away, send immediate notification to Ops Head, COO, and Priti. Finance must initiate the death benefit claim as Priority F&F. HRBP coordinates all family formalities.", "status_options": [{"value": "notified", "label": "Leadership Notified — Priti, COO, Ops Head informed"}, {"value": "death_benefit_filed", "label": "Death Benefit Filed — Finance initiated claim"}, {"value": "ff_in_progress", "label": "F&F In Progress — coordinating with family"}, {"value": "not_applicable", "label": "Not Applicable — outcome was not death"}], "extra_fields": [{"key": "date_of_passing", "label": "Date of Passing", "type": "date", "required": false}, {"key": "notification_notes", "label": "Notification & Coordination Notes", "type": "textarea", "required": false}]}},
   {"number": 10, "action_label": "Post-event family support — within 7 days", "action_detail": "HRBP follows up with family within 7 days. Assist with all documentation, F&F settlement, and death benefit disbursement coordination with Finance. Ensure no outstanding obligations remain.", "owner_role": "hrbp", "sla_working_hours": 168, "escalate_to_role": "ceo", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "status_update", "medium_config": {"instruction": "Complete all post-event family support within 7 days. Ensure F&F settlement is processed, death benefit disbursed (if applicable), and all documentation completed. Confirm zero outstanding obligations.", "status_options": [{"value": "ff_settled", "label": "F&F Settled — all dues cleared"}, {"value": "benefit_disbursed", "label": "Death Benefit Disbursed to family"}, {"value": "documentation_done", "label": "All Documentation Completed"}, {"value": "closed", "label": "Closed — no outstanding obligations"}], "extra_fields": [{"key": "closure_notes", "label": "Closure Notes", "type": "textarea", "required": true}]}}
 ]'::jsonb)

-- ============================================================
-- SOP-10: Maternity Leave Process
-- ============================================================
,('SOP-10', 'SOP-10', 'Maternity Leave Process',
 'End-to-end process for handling maternity leave requests: document validation, commercial impact assessment, BH and Finance approvals, client confirmation for replacement/reinstatement, payroll continuation, and redeployment where required. Regulatory compliance is mandatory — all approvals must be documented.',
 'hrbp_manual',
 ARRAY['K3'],
 'HIGH',
 ARRAY['ML-A', 'ML-B', 'ML-C', 'ML-D', 'ML-E'],
 '[
   {"order": 1, "role": "hrbp", "label": "HRBP",                   "sla_window": "Day 0 to 3 working days (steps 1–4)"},
   {"order": 2, "role": "kam",  "label": "Key Account Manager",     "sla_window": "3 working days (step 5)"},
   {"order": 3, "role": "hrbp", "label": "HRBP (Approval & Close)", "sla_window": "1–2 working days per step (steps 6–10)"}
 ]'::jsonb,
 '[
   {"number": 1,  "action_label": "Receive maternity leave request", "action_detail": "Employee emails HRBP with pregnancy confirmation document and Expected Delivery Date (EDD). HRBP logs the request immediately. Day 0 action — do not delay.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "document", "medium_config": {"instruction": "Upload the pregnancy confirmation document received from the employee. Log the Expected Delivery Date and confirm receipt.", "accepted_formats": ["pdf", "jpg", "jpeg", "png", "docx"], "max_files": 2}},
   {"number": 2,  "action_label": "Validate documents and employee details", "action_detail": "HRBP verifies: pregnancy confirmation validity, employee details, Expected Delivery Date, current deployment/project status. If incomplete, request clarification from employee.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "status_update", "medium_config": {"instruction": "Validate all submitted documents and confirm the details are complete. If anything is missing, select Incomplete and request clarification from the employee before proceeding.", "status_options": [{"value": "validated", "label": "Validated — all documents and details confirmed"}, {"value": "incomplete", "label": "Incomplete — clarification requested from employee"}, {"value": "pending_review", "label": "Pending Review — documents received, checking validity"}], "extra_fields": [{"key": "employee_id", "label": "Employee ID", "type": "text", "required": true}, {"key": "expected_delivery_date", "label": "Expected Delivery Date (EDD)", "type": "date", "required": true}, {"key": "current_project", "label": "Current Project / Deployment", "type": "text", "required": true}, {"key": "validation_notes", "label": "Validation Notes / Clarification Sent", "type": "textarea", "required": false}]}},
   {"number": 3,  "action_label": "Collect commercial / billing details from Billing Team", "action_detail": "Before approaching BH, HRBP must obtain billing details from the Billing Team: PO, Margin, CTC, Margin %, DOJ, Company, Designation, PO End Date, Total Experience. Billing Team to respond within 1 working day.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "form", "medium_config": {"instruction": "Fill in the commercial details received from the Billing Team. Do NOT proceed to BH approval without completing this step.", "form_schema": [{"key": "employee_id", "label": "Employee ID", "type": "text", "required": true}, {"key": "employee_name", "label": "Employee Name", "type": "text", "required": true}, {"key": "company_name", "label": "Client Company", "type": "text", "required": true}, {"key": "designation", "label": "Designation", "type": "text", "required": true}, {"key": "doj", "label": "Date of Joining (DOJ)", "type": "date", "required": true}, {"key": "po_end_date", "label": "PO End Date", "type": "date", "required": true}, {"key": "monthly_po", "label": "PO Amount (Monthly ₹)", "type": "number", "required": true}, {"key": "monthly_margin", "label": "Margin (Monthly ₹)", "type": "number", "required": true}, {"key": "current_ctc", "label": "CTC (Monthly ₹)", "type": "number", "required": true}, {"key": "margin_pct", "label": "Current Margin %", "type": "number", "required": true}, {"key": "total_experience", "label": "Total Experience (Years)", "type": "number", "required": false}, {"key": "maternity_start", "label": "Proposed Leave Start Date", "type": "date", "required": true}, {"key": "maternity_end", "label": "Estimated Leave End Date", "type": "date", "required": true}, {"key": "projected_impact", "label": "Projected Financial Impact (₹)", "type": "number", "required": true}]}},
   {"number": 4,  "action_label": "Send BH approval request — copy KAM to check with client", "action_detail": "HRBP sends approval request to BH with maternity leave summary, EDD, commercial details, and projected financial impact. KAM copied to confirm with client: replacement requirement and reinstatement willingness after leave.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": "ML-A", "hard_gate": null, "kra_ref": "K3", "medium": "email", "medium_config": {"instruction": "Send ML-A approval request email to the Business Head, copying the KAM/Account Manager. Include the commercial details from Step 3. KAM must then check with the client on replacement and reinstatement.", "template_id": "ML-A"}},
   {"number": 5,  "action_label": "KAM confirms client decision — replacement and reinstatement", "action_detail": "KAM contacts client to confirm: (1) Is replacement required during maternity leave? (2) Will reinstatement be allowed after leave? Both answers must be captured and documented.", "owner_role": "kam", "sla_working_hours": 24, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "status_update", "medium_config": {"instruction": "Contact the client and capture their decision on both replacement and reinstatement. This confirmation determines the next branch of the process.", "status_options": [{"value": "reinstatement_confirmed", "label": "Scenario A — Client confirms reinstatement after leave"}, {"value": "replacement_only_no_reinstate", "label": "Scenario B — Client needs replacement only, no reinstatement"}, {"value": "no_replacement_reinstate", "label": "No replacement needed, reinstatement confirmed"}, {"value": "pending_client_response", "label": "Pending — awaiting client response"}], "extra_fields": [{"key": "client_contact", "label": "Client Contact Name", "type": "text", "required": true}, {"key": "client_decision_date", "label": "Date of Client Confirmation", "type": "date", "required": true}, {"key": "replacement_needed", "label": "Replacement Required? (Yes/No)", "type": "text", "required": true}, {"key": "client_notes", "label": "Client Decision Notes", "type": "textarea", "required": true}]}},
   {"number": 6,  "action_label": "HRBP records decision branch and initiates action", "action_detail": "Scenario A (reinstatement): HRBP informs employee, Delivery Team plans interim replacement if required. Scenario B (no reinstatement): maternity end date = project LWD, redeployment process initiated immediately with Delivery Team.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "status_update", "medium_config": {"instruction": "Record the outcome branch based on client confirmation from Step 5. If Scenario B, initiate redeployment with the Delivery Team immediately.", "status_options": [{"value": "scenario_a_reinstate", "label": "Scenario A — Reinstatement Approved, interim replacement planned if needed"}, {"value": "scenario_b_redeploy", "label": "Scenario B — No reinstatement, LWD set, redeployment initiated"}, {"value": "no_replacement_approved", "label": "No replacement needed, reinstatement confirmed, proceeding to approvals"}], "extra_fields": [{"key": "project_lwd", "label": "Project LWD (if Scenario B)", "type": "date", "required": false}, {"key": "redeployment_notes", "label": "Redeployment / Replacement Notes", "type": "textarea", "required": false}]}},
   {"number": 7,  "action_label": "Send Finance approval request to Banita", "action_detail": "After BH approval, HRBP sends case to Finance (Banita) with: employee details, commercial details, projected financial impact, and BH approval confirmation. Finance must respond within 2 working days.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": "ML-B", "hard_gate": null, "kra_ref": "K3", "medium": "email", "medium_config": {"instruction": "Send ML-B Finance approval request to Banita. Include all commercial details and BH approval confirmation. Finance must respond within 2 working days. Do NOT initiate salary release before Finance approval.", "template_id": "ML-B"}},
   {"number": 8,  "action_label": "Inform Timesheet / Payroll SPOC to release salary", "action_detail": "Once Finance approval is received, HRBP informs Timesheet/Payroll SPOC to ensure salary release during the approved maternity leave period. Include all leave dates and Finance approval reference.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": "ML-C", "hard_gate": null, "kra_ref": "K3", "medium": "email", "medium_config": {"instruction": "Send ML-C payroll instruction email to the Timesheet/Payroll SPOC. Include leave start date, leave end date, EDD, and Finance approval date. Salary release must not be initiated without Finance approval.", "template_id": "ML-C"}},
   {"number": 9,  "action_label": "Communicate final status to employee", "action_detail": "HRBP formally informs employee: approval confirmation, client dependency outcome, reinstatement confirmation (Scenario A) or redeployment discussion (Scenario B), payroll/leave next steps.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": "ML-D", "hard_gate": null, "kra_ref": "K3", "medium": "email", "medium_config": {"instruction": "Send employee communication email. Use ML-D (Reinstatement Confirmed) for Scenario A or ML-E (Replacement Only / Redeployment Required) for Scenario B. Confirm the correct template is selected before sending.", "template_id": "ML-D"}},
   {"number": 10, "action_label": "Update tracker and close case", "action_detail": "HRBP updates tracker with: approval dates, financial impact, client decision, reinstatement/replacement status, redeployment status, payroll intimation date, final closure status. Tracker must be updated at every milestone.", "owner_role": "hrbp", "sla_working_hours": 8, "escalate_to_role": "ops_head", "email_template_id": null, "hard_gate": null, "kra_ref": "K3", "medium": "status_update", "medium_config": {"instruction": "Update the tracker with all milestones and mark the final closure status. All fields below are required for audit compliance.", "status_options": [{"value": "closed_reinstated", "label": "Closed — Reinstatement Confirmed"}, {"value": "closed_redeployed", "label": "Closed — Redeployment Initiated"}, {"value": "closed_no_replacement", "label": "Closed — No Replacement, Reinstatement Approved"}, {"value": "in_progress", "label": "In Progress — pending milestone"}], "extra_fields": [{"key": "bh_approval_date", "label": "BH Approval Date", "type": "date", "required": true}, {"key": "finance_approval_date", "label": "Finance Approval Date", "type": "date", "required": true}, {"key": "payroll_intimation_date", "label": "Payroll Intimation Date", "type": "date", "required": true}, {"key": "leave_start_date", "label": "Leave Start Date", "type": "date", "required": true}, {"key": "leave_end_date", "label": "Leave End Date (Estimated)", "type": "date", "required": true}, {"key": "financial_impact", "label": "Total Financial Impact (₹)", "type": "number", "required": true}, {"key": "closure_notes", "label": "Closure Notes", "type": "textarea", "required": false}]}}
 ]'::jsonb)

ON CONFLICT (sop_type) DO NOTHING;
