/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedIncidentEngineRouteImport } from './routes/_authenticated/incident-engine'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunicationRouteImport } from './routes/_authenticated/communication'
import { Route as AuthenticatedCadenceRouteImport } from './routes/_authenticated/cadence'
import { Route as AuthenticatedActivityLogRouteImport } from './routes/_authenticated/activity-log'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated/tickets.index'
import { Route as AuthenticatedExitsIndexRouteImport } from './routes/_authenticated/exits.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedTicketsTicketIdRouteImport } from './routes/_authenticated/tickets.$ticketId'
import { Route as AuthenticatedConsultantsConsultantIdRouteImport } from './routes/_authenticated/consultants.$consultantId'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin.tickets'
import { Route as AuthenticatedAdminConsultantsRouteImport } from './routes/_authenticated/admin.consultants'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncidentEngineRoute =
  AuthenticatedIncidentEngineRouteImport.update({
    id: '/incident-engine',
    path: '/incident-engine',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunicationRoute =
  AuthenticatedCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadenceRoute = AuthenticatedCadenceRouteImport.update({
  id: '/cadence',
  path: '/cadence',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityLogRoute =
  AuthenticatedActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExitsIndexRoute = AuthenticatedExitsIndexRouteImport.update({
  id: '/exits/',
  path: '/exits/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsTicketIdRoute =
  AuthenticatedTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsultantsConsultantIdRoute =
  AuthenticatedConsultantsConsultantIdRouteImport.update({
    id: '/consultants/$consultantId',
    path: '/consultants/$consultantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/admin/tickets',
    path: '/admin/tickets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminConsultantsRoute =
  AuthenticatedAdminConsultantsRouteImport.update({
    id: '/admin/consultants',
    path: '/admin/consultants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/admin/clients',
    path: '/admin/clients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/cadence': typeof AuthenticatedCadenceRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/incident-engine': typeof AuthenticatedIncidentEngineRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/consultants': typeof AuthenticatedAdminConsultantsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/consultants/$consultantId': typeof AuthenticatedConsultantsConsultantIdRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/exits/': typeof AuthenticatedExitsIndexRoute
  '/tickets/': typeof AuthenticatedTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/cadence': typeof AuthenticatedCadenceRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/incident-engine': typeof AuthenticatedIncidentEngineRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/consultants': typeof AuthenticatedAdminConsultantsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/consultants/$consultantId': typeof AuthenticatedConsultantsConsultantIdRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/exits': typeof AuthenticatedExitsIndexRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/_authenticated/activity-log': typeof AuthenticatedActivityLogRoute
  '/_authenticated/cadence': typeof AuthenticatedCadenceRoute
  '/_authenticated/communication': typeof AuthenticatedCommunicationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/incident-engine': typeof AuthenticatedIncidentEngineRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/consultants': typeof AuthenticatedAdminConsultantsRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/consultants/$consultantId': typeof AuthenticatedConsultantsConsultantIdRoute
  '/_authenticated/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/exits/': typeof AuthenticatedExitsIndexRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/activity-log'
    | '/cadence'
    | '/communication'
    | '/dashboard'
    | '/incident-engine'
    | '/notifications'
    | '/profile'
    | '/admin/clients'
    | '/admin/consultants'
    | '/admin/tickets'
    | '/admin/users'
    | '/clients/$clientId'
    | '/consultants/$consultantId'
    | '/tickets/$ticketId'
    | '/admin/'
    | '/clients/'
    | '/exits/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/activity-log'
    | '/cadence'
    | '/communication'
    | '/dashboard'
    | '/incident-engine'
    | '/notifications'
    | '/profile'
    | '/admin/clients'
    | '/admin/consultants'
    | '/admin/tickets'
    | '/admin/users'
    | '/clients/$clientId'
    | '/consultants/$consultantId'
    | '/tickets/$ticketId'
    | '/admin'
    | '/clients'
    | '/exits'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/change-password'
    | '/login'
    | '/_authenticated/activity-log'
    | '/_authenticated/cadence'
    | '/_authenticated/communication'
    | '/_authenticated/dashboard'
    | '/_authenticated/incident-engine'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/consultants'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/users'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/consultants/$consultantId'
    | '/_authenticated/tickets/$ticketId'
    | '/_authenticated/admin/'
    | '/_authenticated/clients/'
    | '/_authenticated/exits/'
    | '/_authenticated/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incident-engine': {
      id: '/_authenticated/incident-engine'
      path: '/incident-engine'
      fullPath: '/incident-engine'
      preLoaderRoute: typeof AuthenticatedIncidentEngineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/communication': {
      id: '/_authenticated/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AuthenticatedCommunicationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadence': {
      id: '/_authenticated/cadence'
      path: '/cadence'
      fullPath: '/cadence'
      preLoaderRoute: typeof AuthenticatedCadenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity-log': {
      id: '/_authenticated/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof AuthenticatedActivityLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exits/': {
      id: '/_authenticated/exits/'
      path: '/exits'
      fullPath: '/exits/'
      preLoaderRoute: typeof AuthenticatedExitsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/$ticketId': {
      id: '/_authenticated/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consultants/$consultantId': {
      id: '/_authenticated/consultants/$consultantId'
      path: '/consultants/$consultantId'
      fullPath: '/consultants/$consultantId'
      preLoaderRoute: typeof AuthenticatedConsultantsConsultantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/consultants': {
      id: '/_authenticated/admin/consultants'
      path: '/admin/consultants'
      fullPath: '/admin/consultants'
      preLoaderRoute: typeof AuthenticatedAdminConsultantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityLogRoute: typeof AuthenticatedActivityLogRoute
  AuthenticatedCadenceRoute: typeof AuthenticatedCadenceRoute
  AuthenticatedCommunicationRoute: typeof AuthenticatedCommunicationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIncidentEngineRoute: typeof AuthenticatedIncidentEngineRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminConsultantsRoute: typeof AuthenticatedAdminConsultantsRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedConsultantsConsultantIdRoute: typeof AuthenticatedConsultantsConsultantIdRoute
  AuthenticatedTicketsTicketIdRoute: typeof AuthenticatedTicketsTicketIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedExitsIndexRoute: typeof AuthenticatedExitsIndexRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityLogRoute: AuthenticatedActivityLogRoute,
  AuthenticatedCadenceRoute: AuthenticatedCadenceRoute,
  AuthenticatedCommunicationRoute: AuthenticatedCommunicationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIncidentEngineRoute: AuthenticatedIncidentEngineRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminConsultantsRoute: AuthenticatedAdminConsultantsRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedConsultantsConsultantIdRoute:
    AuthenticatedConsultantsConsultantIdRoute,
  AuthenticatedTicketsTicketIdRoute: AuthenticatedTicketsTicketIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedExitsIndexRoute: AuthenticatedExitsIndexRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
